### ISSUE TITLE
BigDecimalField focusedProperty.addListener() is not working

### ISSUE THREAD

**Issue by montalbano** [JFXtras/jfxtras-labs#107] opened 2015-02-20 10:18 UTC
I'm using jfxtras-labs-8.0-r3 and I'm having problems using BigDecimalField when I need to catch the focus event inside the textfield control of the spin button.

Apparently the event on focus is not fired when I click inside the spinbutton's textfield, and I don't know why. Please help me, tnx.

**Comment by teabeeoh** [comment] 2015-02-22 12:50
Hi,

thanks for the report, that is obviously currently not working. I had a 
look this morning, but I could not figure a quick solution to this and I 
have to have deeper look as soon as time permits.
@Tom: Same issue with CalendarTextField by the way as I see it. Both 
controls behave different from the normal TextField.

Regards

Thomas

Am 20.02.2015 um 11:18 schrieb montalbano:

**Comment by tbee** [comment] 2015-02-22 17:48
Ok! Then'll take a look as well.

**Comment by tbee** [comment] 2015-02-23 07:00
I see. This most likely is caused by the composition nature of JavaFX. CalendarTextField uses (not extends) a TextField and therefor all event must be explicitely forwarded. Have I ever mentioned I'm not the biggest fan of composition? ;-)

An easy solution would be to bind the focus property of our controls to the focus property of the textfield, but that is not allowed, because they are read only. That also is the problem why it is not possible to set the value in the listener that is in the skin (reacting to typed text). I'm going to drop this in the OpenJFX list.

Tom

**Comment by tbee** [comment] 2015-02-23 08:04
This works:
- create a _public_ focusForwardProperty in the Skin
- listen to the focusProperty of TextField and set the focusForwardProperty accordingly
- listen to the skinProperty in the Control and when set, bind a listener to the focusForwardProperty of the skin that is being set
- in this  listener call setFocused with the value of focusForwardProperty

But is, at the least, not pretty.

Tom

**Comment by montalbano** [comment] 2015-02-23 10:29
Thanks for your response. I don't understand where I have to create the _public_ focusForwardProperty in the Skin.

Gianfranco

**Comment by tbee** [comment] 2015-02-23 10:35
Oh, it is not intended for you, this is for Thomas to implement in the BigDecimalTextField.

**Comment by montalbano** [comment] 2015-02-23 10:38
Oh, sorry. :)

**Comment by montalbano** [comment] 2015-02-25 09:12
When you solve the problem can you upload the new library version to the maven repository? Tnx

**Comment by tbee** [comment] 2015-02-25 09:23
Yes. But there is a nightly build of the latest snapshot as well.

**Comment by montalbano** [comment] 2015-02-25 09:53
I need the jfxtras-labs.jar library to include in my netbeans project. Where can I download it?

**Comment by tbee** [comment] 2015-02-25 10:02
It is in Maven. Download links are under "Use It"  on our website. http://jfxtras.org/

**Comment by montalbano** [comment] 2015-02-25 10:33
Thank you, I have downloaded jfxtras-labs-8.0-r4-20150225.090148-124.jar, I tried to fire a changeListener on focusedProperty with the mouse, but it still doesn't work

**Comment by tbee** [comment] 2015-02-25 10:47
Well, AFAIK, the TextField was not fixed by Thomas yet. So that is correct. Try the same on CalendarTextField.

**Comment by montalbano** [comment] 2015-02-25 15:27
I will wait for the BigDecimalField's update. Tnx

**Comment by montalbano** [comment] 2015-03-02 09:45
Has been solved the problem?

**Comment by montalbano** [comment] 2015-03-02 16:17
Maybe I found the solution to the problem. You need to externalize the TextField control of the SpinButton so that I can attach my listener to that focusedProperty and not to the focusedProperty of the spinbutton. So I need the focusedProperty of the TextField of your control, and I need a method like this: getTextField(). In this manner I can do: mySpinButton.getTextField().focusedProperty(changeListener). Thank you

**Comment by teabeeoh** [comment] 2015-03-02 17:12
Hi Tom,

I also did soem trials, but did not come up with a solution for myself. 
Thanks for looking into this and coming up with a solution that works. I 
implemented it in the BigDecimalField as well, did thorough testing and 
it seems to work.

Cheers

Thomas

Am 23.02.2015 um 09:04 schrieb Tom Eugelink:

**Comment by teabeeoh** [comment] 2015-03-02 17:18
Hmmh, the one thing I did not check was the unit tests and the jenkins build fails. Sorry, will look into it, right away...

**Comment by teabeeoh** [comment] 2015-03-02 20:06
Making the TextField accessible from outside is not wanted by design, 
but applying Tom's solution to the BigDecimalField might be the solution 
to your problem.

Am 02.03.2015 um 17:17 schrieb montalbano:

**Comment by tbee** [comment] 2015-03-02 20:07
Good work Thomas

**Comment by teabeeoh** [comment] 2015-03-02 20:16
Thanks, hope that I found all issues now.

Am 02.03.2015 um 21:07 schrieb Tom Eugelink:

**Comment by montalbano** [comment] 2015-03-02 21:11
What snapshot I have to downoad to find the solution to my problem? Tnx

**Comment by tbee** [comment] 2015-03-03 06:15
Latest you can find on jfxtras.org, r4-snapshot

**Comment by montalbano** [comment] 2015-03-03 09:33
Now it works...Thank you very much...you are very kind and professional.... ;)

**Comment by leubac** [comment] 2015-03-04 08:41
I'm facing the same problem with JavaFX 2 (jfxtras-labs-2.2-r6-20150303.090104-441.jar).
Could you also put this fix into this version please ?

**Comment by tbee** [comment] 2015-05-28 18:46
We're not backporting to 2.2; the changes in JavaFX are too big to maintain two branches.

**Closed as completed by tbee** 2015-05-28 18:46 UTC

**Comment by teabeeoh** [comment] 2015-05-29 12:47
Thanks for the clean up at jfxtras, Tom.

Cheers

Thomas

Am 28.05.2015 um 20:46 schrieb Tom Eugelink notifications@github.com:
